/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Generated from the docs/ tree: folder order comes from _category_.json,
  // page order from each page's sidebar_position.
  guide: [{ type: 'autogenerated', dirName: '.' }],
};

module.exports = sidebars;
